# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm
    mappings:
        avatar:
            uri_prefix: /images/personnes
            upload_destination: '%kernel.project_dir%/public/images/personnes'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true